/**
 * Reads the game's exported content at build time.
 *
 * `scripts/export-content.cjs` already emits the game's data as JSON into
 * `unity/Assets/Isoperia/Resources/Content/` so the Unity port and the
 * TypeScript build share one source. The website is simply a third consumer of
 * that same export.
 *
 * WHY THIS RATHER THAN WRITING THE NUMBERS INTO THE PAGE
 * A features page that lists "12 skills" as prose is a claim that rots the
 * moment someone adds a thirteenth. Reading the export means the page cannot
 * disagree with the game, and `npm test` regenerates the export, so a stale
 * count fails CI rather than shipping.
 */
import fs from "node:fs";
import path from "node:path";

/**
 * Finds the exported content directory by walking up from the working
 * directory.
 *
 * Not resolved from `import.meta.url`: this module is bundled before it runs,
 * so at build time that URL points into `.astro/` rather than `src/lib/`.
 */
function findContentDir(): string {
  const rel = "unity/Assets/Isoperia/Resources/Content";
  let dir = process.cwd();
  for (let i = 0; i < 6; i++) {
    const candidate = path.join(dir, rel);
    if (fs.existsSync(candidate)) return candidate;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error(
    `Could not find ${rel} walking up from ${process.cwd()}. It is generated by ` +
      `scripts/export-content.cjs (npm test regenerates it). The features page ` +
      `reads its numbers from there, so the build stops rather than inventing them.`,
  );
}

const DIR = findContentDir();

function load<T>(name: string): T {
  return JSON.parse(fs.readFileSync(path.join(DIR, `${name}.json`), "utf8")) as T;
}

interface ResourceNode {
  skill: string;
  levelReq: number;
  masteryKey: string;
  ticksPerAction: number;
  depletes: boolean;
  maxUses: number;
}

interface Building {
  name: string;
  effect?: string;
}

const skills = load<{
  SKILL_IDS: string[];
  COMBAT_SKILLS: string[];
  CRAFT_SKILLS: string[];
  RESOURCES: Record<string, ResourceNode>;
}>("skills");

interface Item {
  /** Experience per gathered unit, keyed by skill. The game falls back to 5. */
  xp?: Record<string, number>;
}

const items = load<{ ITEMS: Record<string, Item> }>("items");
interface Monster {
  name: string;
  level: number;
  hp: number;
  maxHit: number;
}

const combat = load<{
  MONSTERS: Record<string, Monster>;
  WEAPONS: Record<string, unknown>;
}>("combat");
const buildings = load<{ BUILDINGS: Record<string, Building>; MAX_BUILD_LEVEL: number }>(
  "buildings",
);
const recipes = load<{ RECIPES: Record<string, unknown> }>("recipes");
const achievements = load<{ ACHIEVEMENTS: Record<string, unknown> }>("achievements");

/** Headline counts, all read from the export rather than written by hand. */
export const counts = {
  skills: skills.SKILL_IDS.length,
  combatSkills: skills.COMBAT_SKILLS.length,
  craftSkills: skills.CRAFT_SKILLS.length,
  items: Object.keys(items.ITEMS).length,
  monsters: Object.keys(combat.MONSTERS).length,
  weapons: Object.keys(combat.WEAPONS).length,
  buildings: Object.keys(buildings.BUILDINGS).length,
  recipes: Object.keys(recipes.RECIPES).length,
  achievements: Object.keys(achievements.ACHIEVEMENTS).length,
  resourceNodes: Object.keys(skills.RESOURCES).length,
  maxBuildLevel: buildings.MAX_BUILD_LEVEL,
} as const;

const TITLES: Record<string, string> = {
  attack: "Attack",
  strength: "Strength",
  defense: "Defence",
  hitpoints: "Hitpoints",
  cooking: "Cooking",
  smithing: "Smithing",
  carpentry: "Carpentry",
  construction: "Construction",
  farming: "Farming",
  woodcutting: "Woodcutting",
  mining: "Mining",
  fishing: "Fishing",
};

export function skillName(id: string): string {
  return TITLES[id] ?? id;
}

export interface SkillGroup {
  label: string;
  note: string;
  ids: string[];
}

/**
 * The skills, grouped the way the game groups them.
 *
 * "Gathering" is derived rather than listed: it is whatever is left once the
 * combat and craft sets are removed, so adding a skill to the export puts it in
 * the right group here with no edit.
 */
export function skillGroups(): SkillGroup[] {
  const combatSet = new Set(skills.COMBAT_SKILLS);
  const craftSet = new Set(skills.CRAFT_SKILLS);
  const rest = skills.SKILL_IDS.filter((id) => !combatSet.has(id) && !craftSet.has(id));

  return [
    {
      label: "Combat",
      note: "Tick-based, with OSRS-style damage rolls and auto-eat.",
      ids: skills.COMBAT_SKILLS,
    },
    {
      label: "Crafting",
      note: "Each needs the matching settlement building before its recipes unlock.",
      ids: skills.CRAFT_SKILLS,
    },
    {
      label: "Gathering and settlement",
      note: "Nodes deplete and respawn; per-item mastery earns double drops and speed.",
      ids: rest,
    },
  ];
}

export interface NodeRow {
  id: string;
  skill: string;
  levelReq: number;
  ticksPerAction: number;
  maxUses: number;
}

/** Every gatherable node, sorted by skill then by level requirement. */
export function resourceNodes(): NodeRow[] {
  return Object.entries(skills.RESOURCES)
    .map(([id, r]) => ({
      id,
      skill: skillName(r.skill),
      levelReq: r.levelReq,
      ticksPerAction: r.ticksPerAction,
      maxUses: r.maxUses,
    }))
    .sort((a, b) =>
      a.skill === b.skill ? a.levelReq - b.levelReq : a.skill < b.skill ? -1 : 1,
    );
}

export interface BuildingRow {
  id: string;
  name: string;
  effect: string;
}

export function buildingRows(): BuildingRow[] {
  return Object.entries(buildings.BUILDINGS)
    .map(([id, b]) => ({ id, name: b.name, effect: b.effect ?? "" }))
    .sort((a, b) => (a.name < b.name ? -1 : 1));
}

/** A readable node id: "rock_coal" -> "Coal rock". */
export function nodeLabel(id: string): string {
  const [kind, ...rest] = id.split("_");
  const what = rest.join(" ");
  const noun = kind === "water" ? "spot" : (kind ?? "");
  return `${what.charAt(0).toUpperCase()}${what.slice(1)} ${noun}`.trim();
}

/**
 * One monster's public-facing numbers, straight out of the combat export.
 *
 * Throws on an unknown id rather than returning undefined. A creature card that
 * silently rendered blank stats would look like a styling bug and survive
 * review; a build that stops names the id nobody renamed.
 */
export interface MonsterFacts {
  name: string;
  level: number;
  hp: number;
  maxHit: number;
}

export function monster(id: string): MonsterFacts {
  const m = combat.MONSTERS[id];
  if (!m) {
    throw new Error(
      `No monster "${id}" in the combat export. The world page names it, so the ` +
        `build stops rather than shipping a card with no numbers on it.`,
    );
  }
  return { name: m.name, level: m.level, hp: m.hp, maxHit: m.maxHit };
}

/** The engine's tick, in milliseconds. The site's motion scale derives from it. */
export const TICK_MS = 600;

/* ---------------------------------------------------------------------------
 * The bestiary, for /bestiary.
 *
 * Drop tables are stored as WEIGHTS, which is the right shape for the engine
 * to roll against and the wrong shape for a person to read: "weight 140" tells
 * you nothing until you know the total. Weights are converted to real
 * probabilities here, once, at build time.
 *
 * `tertiary` and `petTable` entries already carry an explicit `chance`, so they
 * pass through untouched — mixing the two would silently rescale them.
 */
export interface Drop {
  itemId: string;
  label: string;
  /** 0–1. From the weight share for main drops, verbatim for the rest. */
  chance: number;
  min: number;
  max: number;
  table: "main" | "tertiary" | "pet";
}

export interface Beast {
  id: string;
  name: string;
  level: number;
  hp: number;
  maxHit: number;
  /** Ticks between the monster's attacks. */
  attackTick: number;
  aggroRange: number;
  ranged: boolean;
  boss: boolean;
  respawnSeconds: number;
  /** Experience per kill, summed across the skills it trains. */
  xpTotal: number;
  xp: { skill: string; amount: number }[];
  drops: Drop[];
}

interface RawDrop {
  itemId: string;
  weight?: number;
  chance?: number;
  min?: number;
  max?: number;
}

interface RawMonster {
  id: string;
  name: string;
  level: number;
  hp: number;
  maxHit: number;
  attackTick: number;
  aggroRange: number;
  ranged?: boolean;
  boss?: boolean;
  respawnMs: number;
  xp: Record<string, number>;
  main?: RawDrop[];
  tertiary?: RawDrop[];
  petTable?: RawDrop[];
}

const itemNames = load<{ ITEMS: Record<string, { name?: string }> }>("items").ITEMS;

/** "raw_rat_meat" -> "Raw Rat Meat", for anything the item table does not name. */
function itemLabel(id: string): string {
  const named = itemNames[id]?.name;
  if (named) return named;
  return id
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

export function bestiary(): Beast[] {
  const raw = combat.MONSTERS as unknown as Record<string, RawMonster>;
  return Object.values(raw)
    .map((m) => {
      const main = m.main ?? [];
      const total = main.reduce((sum, d) => sum + (d.weight ?? 0), 0);
      const drops: Drop[] = [
        ...main.map((d) => ({
          itemId: d.itemId,
          label: itemLabel(d.itemId),
          chance: total > 0 ? (d.weight ?? 0) / total : 0,
          min: d.min ?? 1,
          max: d.max ?? 1,
          table: "main" as const,
        })),
        ...(m.tertiary ?? []).map((d) => ({
          itemId: d.itemId,
          label: itemLabel(d.itemId),
          chance: d.chance ?? 0,
          min: d.min ?? 1,
          max: d.max ?? 1,
          table: "tertiary" as const,
        })),
        ...(m.petTable ?? []).map((d) => ({
          itemId: d.itemId,
          label: itemLabel(d.itemId),
          chance: d.chance ?? 0,
          min: 1,
          max: 1,
          table: "pet" as const,
        })),
      ].sort((a, b) => b.chance - a.chance);

      const xp = Object.entries(m.xp ?? {})
        .map(([skill, amount]) => ({ skill: skillName(skill), amount }))
        .sort((a, b) => b.amount - a.amount);

      return {
        id: m.id,
        name: m.name,
        level: m.level,
        hp: m.hp,
        maxHit: m.maxHit,
        attackTick: m.attackTick,
        aggroRange: m.aggroRange,
        ranged: Boolean(m.ranged),
        boss: Boolean(m.boss),
        respawnSeconds: Math.round(m.respawnMs / 1000),
        xpTotal: xp.reduce((s, x) => s + x.amount, 0),
        xp,
        drops,
      };
    })
    .sort((a, b) => a.level - b.level || (a.name < b.name ? -1 : 1));
}
