// GENERATED by scripts/gen-model-manifest.cjs — do not edit by hand.
// Lists the GLBs present in public/models at build time, so the loader never
// requests a model that isn't shipped.

export const AVAILABLE_MODELS: ReadonlySet<string> = new Set(["cave_brute","forest_ogre","hero","villager"]);

export function hasModel(name: string): boolean {
  // An empty manifest means the generator hasn't run; don't block loading then.
  return AVAILABLE_MODELS.size === 0 || AVAILABLE_MODELS.has(name);
}

/** Shared animation clips present in public/models/clips (see ClipLibrary). */
export const AVAILABLE_CLIPS: ReadonlySet<string> = new Set(["hero_idle","hero_walk"]);

export function hasClip(name: string): boolean {
  return AVAILABLE_CLIPS.size === 0 || AVAILABLE_CLIPS.has(name);
}
