#!/usr/bin/env bash
# Deploys the WebGL build and writes the evidence to unity/deploy-report.txt.
#
# The Editor writes unity/build-report.txt; this covers the half it cannot see.
# The header check in particular is the single thing separating "deployed" from
# "actually loads": if Content-Type and Content-Encoding are wrong on the wasm,
# the Unity loader hangs on the progress bar or throws "Unable to parse", and no
# amount of debugging inside Unity will find it.
#
# Usage:   scripts/deploy-report.sh                 # deploy, then verify
#          scripts/deploy-report.sh https://site    # skip deploy, verify only
set -uo pipefail

BUILD_DIR="unity/WebGLBuild"
REPORT="unity/deploy-report.txt"
SITE="${1:-}"

if [ ! -d "$BUILD_DIR" ]; then
  echo "error: $BUILD_DIR does not exist. Run the WebGL build first." >&2
  exit 1
fi

{
  echo "# Isoperia deploy report"
  echo "# Generated by scripts/deploy-report.sh. Commit this file."
  echo
  echo "deployed_at_utc: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo "build_dir_size:  $(du -sh "$BUILD_DIR" | cut -f1)"
  echo "build_subdir:    $(du -sh "$BUILD_DIR/Build" 2>/dev/null | cut -f1 || echo 'MISSING')"
} > "$REPORT"

if [ -z "$SITE" ]; then
  echo "==> deploying $BUILD_DIR"
  DEPLOY_LOG=$(npx netlify-cli deploy --dir "$BUILD_DIR" --prod --no-build 2>&1)
  echo "$DEPLOY_LOG"

  # Netlify prints two URLs: an immutable per-deploy one
  # (https://<hash>--<site>.netlify.app) and the production one
  # (https://<site>.netlify.app). Prefer production -- it is the URL people
  # actually get shared, the one the PWA installs under, and the only one that
  # keeps working after the next deploy. Round 3 captured the per-deploy URL,
  # which verified a real deploy but not the address anyone would use.
  SITE=$(echo "$DEPLOY_LOG" | grep -oE 'https://[a-zA-Z0-9-]+\.netlify\.app' | grep -v -- '--' | tail -1)
  [ -z "$SITE" ] && SITE=$(echo "$DEPLOY_LOG" | grep -oE 'https://[a-zA-Z0-9.-]+\.netlify\.app' | tail -1)

  if [ -z "$SITE" ]; then
    echo "url: COULD NOT PARSE FROM DEPLOY OUTPUT -- paste it in by hand" >> "$REPORT"
    echo >> "$REPORT"
    echo "## deploy output" >> "$REPORT"
    echo "$DEPLOY_LOG" >> "$REPORT"
    echo "warning: could not parse the deployed URL; see $REPORT" >&2
    exit 1
  fi
fi

echo "url: $SITE" >> "$REPORT"
echo >> "$REPORT"

# --- the header check ---------------------------------------------------------
WASM=$(ls "$BUILD_DIR/Build" | grep -E '\.wasm\.(br|gz)$' | head -1)
DATA=$(ls "$BUILD_DIR/Build" | grep -E '\.data\.(br|gz)$' | head -1)

{
  echo "## Header check (the thing that decides whether it loads at all)"
  echo
} >> "$REPORT"

check() {
  local file="$1" expect_type="$2"
  [ -z "$file" ] && { echo "  (no matching file in Build/)" >> "$REPORT"; return; }

  local url="$SITE/Build/$file"
  local hdrs
  hdrs=$(curl -sSI --max-time 30 "$url" 2>&1)

  {
    echo "### $file"
    echo "$hdrs" | grep -iE '^(HTTP/|content-type|content-encoding|content-length)' || echo "$hdrs"
  } >> "$REPORT"

  local ctype cenc
  ctype=$(echo "$hdrs" | grep -i '^content-type:' | tr -d '\r' | awk '{print $2}')
  cenc=$(echo "$hdrs" | grep -i '^content-encoding:' | tr -d '\r' | awk '{print $2}')

  if [ "$ctype" = "$expect_type" ] && [ -n "$cenc" ]; then
    echo "VERDICT: OK" >> "$REPORT"
  else
    {
      echo "VERDICT: WRONG -- expected content-type: $expect_type plus a content-encoding."
      echo "         The loader will hang or throw \"Unable to parse\"."
      echo "         Fix the host config before touching Unity."
    } >> "$REPORT"
  fi
  echo >> "$REPORT"
}

check "$WASM" "application/wasm"
check "$DATA" "application/octet-stream"

echo "==> wrote $REPORT"
grep -E '^(url|VERDICT)' "$REPORT"
