#!/usr/bin/env node
/**
 * Emits web/src/styles/tokens.css from web/src/styles/tokens.json.
 *
 * The JSON is the source of truth because scripts/verify-tokens.cjs audits it
 * for contrast; generating the CSS from the same file means the stylesheet the
 * browser gets and the palette the audit passed cannot drift apart.
 *
 * THEME STRATEGY
 * Three blocks, in this order, and the order matters:
 *   1. :root                                  -> the complete light palette.
 *   2. @media (prefers-color-scheme: dark)
 *        :root:not([data-theme="light"])      -> dark for people who asked the
 *                                                OS for it and have not
 *                                                overridden it on this site.
 *   3. :root[data-theme="dark"]               -> an explicit site-level choice,
 *                                                which must win in both
 *                                                directions.
 *
 * Every colour is fully defined in (1). A token whose only definition lives
 * inside a media query is invisible to anyone whose OS says light, which is the
 * classic way a "dark-first" palette ships a broken light mode.
 *
 * Output is gitignored and regenerated on build — there is nothing to keep in
 * sync, and no stale generated file for CI to trip over.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "web/src/styles/tokens.json");
const OUT = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.join(ROOT, "web/src/styles/tokens.css");

const spec = JSON.parse(fs.readFileSync(SRC, "utf8"));

const isMeta = (k) => k.startsWith("$");
const entries = (o) => Object.entries(o).filter(([k]) => !isMeta(k));

function declare(obj, prefix, indent = "  ") {
  return entries(obj)
    .map(([k, v]) => `${indent}--${prefix}${k}: ${v};`)
    .join("\n");
}

const L = [];

L.push(`/* GENERATED by scripts/gen-tokens.cjs from web/src/styles/tokens.json.
 * Do not edit — edit the JSON, which is what the contrast audit reads.
 *
 * Concept: ${spec.meta.concept}
 *   light: ${spec.meta.lightIs}
 *   dark:  ${spec.meta.darkIs}
 *
 * Contrast is verified by scripts/verify-tokens.cjs (npm run verify:tokens),
 * which runs in CI. Changing a colour here does nothing; changing it in the
 * JSON without clearing the audit fails the build.
 */`);
L.push("");

// --- theme-independent scales ------------------------------------------------
L.push(":root {");
L.push("  /* Type stacks. Google Fonts only — blueprint §8.1 permits no other");
L.push("     external font host. Each ends in a real system fallback. */");
for (const role of ["display", "body", "mono"]) {
  L.push(`  --font-${role}: ${spec.fonts[role].stack};`);
}
L.push("");
L.push("  /* Fluid type scale (~1.25 mobile -> ~1.333 desktop). */");
L.push(declare(spec.scales.type, "text-"));
L.push("");
L.push(declare(spec.scales.leading, "leading-"));
L.push("");
L.push(declare(spec.scales.tracking, "tracking-"));
L.push("");
L.push(declare(spec.scales.measure, "measure-"));
L.push("");
L.push("  /* 4px base, 8px rhythm above 16. */");
L.push(declare(spec.scales.space, "space-"));
L.push("");
L.push(declare(spec.scales.radius, "radius-"));
L.push("");
L.push("  /* The world moves slowly; the interface answers fast. */");
L.push(declare(spec.scales.motion, ""));
L.push("");
L.push(declare(spec.scales.layout, "layout-"));
L.push("}");
L.push("");

// --- light (the base) --------------------------------------------------------
L.push("/* Light — parchment. The complete palette lives here so that no token");
L.push("   depends on a media query being matched. */");
L.push(":root {");
L.push("  color-scheme: light;");
L.push(declare(spec.themes.light, ""));
L.push("}");
L.push("");

// --- dark --------------------------------------------------------------------
const darkBody = declare(spec.themes.dark, "", "    ");

L.push("/* Dark — the game's HUD. Applied when the OS asks for dark AND the");
L.push("   viewer has not explicitly chosen light on this site. */");
L.push("@media (prefers-color-scheme: dark) {");
L.push('  :root:not([data-theme="light"]) {');
L.push("    color-scheme: dark;");
L.push(darkBody);
L.push("  }");
L.push("}");
L.push("");
L.push("/* An explicit site-level choice wins over the OS, in both directions. */");
L.push(':root[data-theme="dark"] {');
L.push("  color-scheme: dark;");
L.push(darkBody);
L.push("}");
L.push("");

// --- reduced motion ----------------------------------------------------------
L.push(`/* Blueprint §6.1.5 — reduced motion is a designed state, not a kill switch.
 * Collapsing the DURATION tokens (rather than blanket-killing animation) means
 * everything still arrives in its final state and nothing that relies on an
 * animation completing is left half-applied; it simply arrives without
 * travelling. Opacity and colour transitions stay perceptible.
 */`);
L.push("@media (prefers-reduced-motion: reduce) {");
L.push("  :root {");
L.push("    --dur-instant: 0.01ms;");
L.push("    --dur-quick: 0.01ms;");
L.push("    --dur-base: 0.01ms;");
L.push("    --dur-slow: 0.01ms;");
L.push("    --dur-world: 0.01ms;");
L.push("    --stagger: 0ms;");
L.push("  }");
L.push("}");
L.push("");

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, L.join("\n"));

const count = entries(spec.themes.light).length;
console.log(`gen-tokens: wrote ${path.relative(ROOT, OUT)}`);
console.log(`  themes:  ${Object.keys(spec.themes).filter((k) => !isMeta(k)).join(", ")}`);
console.log(`  colours: ${count} per theme`);
